### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by jgollenz** [nushell/tree-sitter-nu#1]
Do you have any plans for syntax highlighting in this repo? It appears common that treesitter repos (I sampled cpp, js and python) do have `highlights.scm` files. My general experience so far was that syntax highlighting starts working once I install the parser with `TSInstall`.

I started looking into it and if you don't mind, I'd like to give it a try :)

**Comment by fdncred** [comment]
I was planning on it but wanted to finish the syntax first. I'm fine with any positive contribution at any time.

**Comment by jgollenz** [comment]
I see. I'm new to tree-sitter in general, so it doesn't really matter what I work on, it will be trial-and-error either way.

May I ask what your workflow is? So far I managed to get the parser working by itself and add it to neovim where I can inspect it in ts-playground (although it is not updating when the buffer changes). However, the syntax highlighting module is not enabled and I don't know how I can do so. Running `tree-sitter highlight some-file.nu` works fine, but no highlighting inside neovim.

**Comment by fdncred** [comment]
My workflow is maybe less than that. I just do what I put in the read me. For inspiration, you can see how the `helix` editor shows the syntax highlighting. Someone contributed the scm files a few months ago.

**Comment by jgollenz** [comment]
> see how the helix editor shows the syntax highlighting

could you please drop me a link to it? :)

**Comment by fdncred** [comment]
no problem https://github.com/helix-editor/helix/tree/master/runtime/queries/nu

**Comment by Feel-ix-343** [comment]
Can this be closed? TSInstall nu enables highlighting

**Comment by fdncred** [comment]
The syntax highlighting is minimal and can be made better via queries.

**Comment by mrdgo** [comment]
I believe that this issue can be closed. There are only specific issues that need to be specifically addressed.
