### ISSUE TITLE
Error on opening *.nu files

### ISSUE THREAD

**Issue by PAF13** [nushell/tree-sitter-nu#107]
after adding the Lazy dependencies to my "nvim-treesitter/nvim-treesitter"  script i get the error below.

I am not sure where to start looking to find the problem. My first guess is that it is compiled with zig but i cant get the other compilers to work right now.

`Error in decoration provider treesitter/highlighter.win:
Error executing lua: .../current/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 221:19. Invalid node type "long_flag_identifier":         
(param_long_flag (long_flag_identifier) @variable.parameter)
stack traceback:
    [C]: in function '_ts_parse_query'
    .../current/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
    ...vim/current/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
    ...vim/current/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
    ...nt/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
    ...nt/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
    ...nt/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
    ...t/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
    ...nt/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prep `

**Comment by fdncred** [comment]
It looks like a [recent PR](https://github.com/nushell/tree-sitter-nu/pull/105) broke the highlights.scm. @mrdgo Do you have time to look into this?

**Comment by mrdgo** [comment]
Interesting. Sure, I will look into this!

**Comment by PAF13** [comment]
I dont know yet how treesitter works so I just used `TSInstall nu` and did not use `TSUpdate`. It works now, thank you.

**Comment by mrdgo** [comment]
Glad to help!

Then please also update your config according to #108

**Comment by fdncred** [comment]
But the problem is that the highlights.scm file doesn't work with the current syntax. `TSInstall nu` must be using an old ... something?

**Comment by mrdgo** [comment]
No, I updated it accordingly. If you look at it, there are occurrences of `long_flag_identifier` in lines 221 and 225 :)

**Comment by fdncred** [comment]
but if i copy those *.scm files to a folder that has the queries on my system, i get the same error.

**Comment by mrdgo** [comment]
This is no `invalid node type: long_flag_identifier`. This is a different problem. Why do you even copy the files there? It looks as if you provoke a version conflict.

**Comment by mrdgo** [comment]
Hmm, so you take the manual installation route?

**Comment by fdncred** [comment]
> Hmm, so you take the manual installation route?

It's just a way to validate. Yes, right now I'm manually configuring tree-sitter-nu in my nvim.

**Comment by mrdgo** [comment]
Aaaah okay, then I am sorry for my provocative comment!

And you have the same config and copied the files to the location that you know for sure, are loaded by nvim? And you ran `:TSUpdate nu` afterwards?

**Comment by fdncred** [comment]
I'm not familiar with `:TSUpdate nu`. What exactly does it do? Maybe update the latest tree-sitter-nu grammar?

**Comment by mrdgo** [comment]
Yes, it gets the latest version of `src/parser.c` that you specify in `parser_config.nu.install_info` in your nvim config, compiles it and puts the compiled binary into your tree-sitter rtp (don't ask me exactly where). This is the way to use the latest grammar.

If you copied the `*.scm` files without that, then you probably ran an old parser with the new highlights, which is incompatible. Since your screenshot, there were some commits on nvim's tree-sitter plugin and you probably have a `build = ":TSUpdate"` there and your problem should hopefully have been resolved :pray:

**Comment by fdncred** [comment]
Ok, I figured out that I can't be editing a nushell script when I do `:TSInstall nu` because of Windows sharing violations. After doing that things look normal again. Although I'm still puzzled why the *.scm files wouldn't work. Maybe they'd work now that I did the TSInstall?
![image](https://github.com/user-attachments/assets/1ef84af0-bf7e-4963-b5c6-39294843354f)

**Comment by mrdgo** [comment]
Seems deliberate to me:
![image](https://github.com/user-attachments/assets/a0db6544-4de0-4d1b-a145-e0ebd2790b4a)
We see the cursor on a variable, it being correctly identified as a variable, and styled white

**Comment by mrdgo** [comment]
I am happy, that everything works again :) Yeah, when I created my first grammar and highlights, I went through a lot of pain learning the way to apply tree-sitter changes in an editor session.

**Comment by fdncred** [comment]
> I am happy, that everything works again :) Yeah, when I created my first grammar and highlights, I went through a lot of pain learning the way to apply tree-sitter changes in an editor session.
> 
> If you have more questions about why and how, chat on Discord?

sounds good. thanks for the back and forth here. i'm satisfied for now since the TSInstall worked. Appreciate all your work and educating me a bit.
