### ISSUE TITLE
Provide a sublime-syntax

### ISSUE THREAD

**Issue by mrdgo** [nushell/tree-sitter-nu#111]
Probably fits more in here than general nushell.

There is [bat](https://github.com/sharkdp/bat), a cat (`man 1 cat`) clone with syntax highlighting capabilities. It uses the [sublime syntax](https://www.sublimetext.com/docs/syntax.html) specification ([manual](https://docs.sublimetext.io/guide/extensibility/syntaxdefs.html)), so we would support two new tools with one new implementation of nu's grammar. And maybe even more.

Just to keep this idea documented.

**Comment by fdncred** [comment]
There are already 2 sublime syntaxes listed here https://github.com/nushell/awesome-nu?tab=readme-ov-file#editor-extensions. I like the idea of having bat recognize nushell code though but I'm not sure it belongs in this repo?
