### ISSUE TITLE
Emacs tree-sitter major mode

### ISSUE THREAD

**Issue by rhz** [nushell/tree-sitter-nu#126]
Hi. I wonder if [writing an Emacs major mode based on the tree-sitter grammar](https://www.masteringemacs.org/article/lets-write-a-treesitter-major-mode) for Nu is among the goals of this project. If so, this is a feature request `:)`.

**Comment by 132ikl** [comment]
There is also https://github.com/herbertjones/nushell-ts-mode

**Comment by rhz** [comment]
> There is also https://github.com/herbertjones/nushell-ts-mode

Thank you! This is what I was looking for.
