### ISSUE TITLE
setting env vars bash style produces errors

### ISSUE THREAD

**Issue by fdncred** [nushell/tree-sitter-nu#146]
This is from nushell's toolkit.nu file
![image](https://github.com/user-attachments/assets/037042d5-5fc4-4035-91e3-11ecfe7baf58)

You can see that setting an env var and running a command, bash style, produces an error.
```nushell
_EXTRA_=bin nu .github/workflows/release-pkg.nu
```

**Comment by blindFS** [comment]
This would introduce new highlight query then. Some extra manual labor for the maintainers of nvim-treesitter 😂

**Comment by fdncred** [comment]
LOL, i'm ok with that. i'd just rather not have errors if we can help it.

**Comment by blindFS** [comment]
> LOL, i'm ok with that. i'd just rather not have errors if we can help it.

I'll see what I can do. Maybe only fix the parser to get rid of the error, and stash the new query to the next major breaking change.
