### ISSUE TITLE
Cannot (re)install on macOS arm64 from Neovim

### ISSUE THREAD

**Issue by acidghost** [nushell/tree-sitter-nu#155]
I get the following error when trying to update:

```
nvim-treesitter[nu]: Error during compilation
Undefined symbols for architecture arm64:
  "_tree_sitter_nu_external_scanner_create", referenced from:
      _tree_sitter_nu.language in parser-04dfe8.o
  "_tree_sitter_nu_external_scanner_deserialize", referenced from:
      _tree_sitter_nu.language in parser-04dfe8.o
  "_tree_sitter_nu_external_scanner_destroy", referenced from:
      _tree_sitter_nu.language in parser-04dfe8.o
  "_tree_sitter_nu_external_scanner_scan", referenced from:
      _tree_sitter_nu.language in parser-04dfe8.o
  "_tree_sitter_nu_external_scanner_serialize", referenced from:
      _tree_sitter_nu.language in parser-04dfe8.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`nvim-treesitter` health check:

```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.4 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 16.0.0 (clang-1600.0.26.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "24.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030"
} 
```

Let me know if I can provide more info.

**Comment by blindFS** [comment]
Thanks for reporting the bug.
Since I don't have that type of device at hand, I'd like to ask for your help to figure out the cause.

Two things I'd like to know:
1. Does `:TSInstallFromGrammar nu` work for you? 
2. What about other parsers, like bash?

@mrdgo Do you have any idea that we may need to regenerate some auxiliary files with the latest tree-sitter-cli? I have a vague impression that there're some compatibility issues of late tree-sitter versions.

**Comment by acidghost** [comment]
>     1. Does `:TSInstallFromGrammar nu` work for you?

Yes, that installed fine.
 
>     2. What about other parsers, like bash?

I tried perl and it worked.

> How do you setup treesitter? Do you mind sharing?

I install it via `vim-plug` (https://github.com/acidghost/dotfiles/blob/aa69fbc1e2815de8a771fd33b87a80946f43fad3/vim/vimrc#L77). Not sure what you mean by setup but those are dotfiles I'm currently using.

**Comment by blindFS** [comment]
@acidghost what if you simply clone this repo and run `make`, will it output the same ld error?

**Comment by mrdgo** [comment]
From the docs:
```
		Feature names can be:
		1.  Nvim version. For example the "nvim-0.2.1" feature means
		    that Nvim is version 0.2.1 or later: >vim
			if has("nvim-0.2.1")
			  " ...
			endif
```

In your config:
```vim
if has('nvim')
    if has('nvim-0.10')
        Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
    elseif has('nvim-0.9.2')
        Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate',
            \ 'commit': 'cfc6f2c117aaaa82f19bcce44deec2c194d900ab' }
            " v0.9.3
    elseif has('nvim-0.9.1')
        Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate',
            \ 'commit': 'f197a15b0d1e8d555263af20add51450e5aaa1f0' }
            " v0.9.2
    else
        Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate',
            \ 'commit': '63260da18bf273c76b8e2ea0db84eb901cab49ce' }
            " v0.9.1
    endif
    if has('nvim-0.7')
        Plug 'LhKipp/nvim-nu', { 'do': ':TSInstall nu' }
        Plug 'Olical/conjure'
    endif
endif
```

So you install both ts and nvim-nu, they both install a parser and highlights. Could you try uninstalling `nvim-nu` and try again?

**Comment by acidghost** [comment]
@mrdgo `nvim-nu` recently removed the feature that installed their grammar (see https://github.com/LhKipp/nvim-nu/commit/3a25a60e46ba07f04a5930126295ccf3f68092ab#diff-71a29d1fb463710bda3b2a74683ccd58119ab2cf5ec3daaaf027bc6d6aa7a181L1-L10).

I think I see the error now because I updated `nvim-nu` and now I fetch the grammar in this repository instead.

Moreover, the LSP feature is now also supported by default in [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/blob/3eaab290c73c139d890e5da8a99dc76c274e03d5/doc/configs.md?plain=1#L6743), so I don't see any value in `nvim-nu` (unless I'm missing something).

Let me try to uninstall `nvim-nu`, uninstall any nu grammar, re-install [the default one](https://github.com/nvim-treesitter/nvim-treesitter/blob/28591731d84c2fc18ddda60e1d53da24c31c4987/lua/nvim-treesitter/parsers.lua#L1475) (which is this repo) and see if I succeed and miss any feature.

**Comment by acidghost** [comment]
It seems like everything is working (grammar and LSP). It might have been some kind of caching issue 🤷 

I'll try on a clean install too and reopen if I have problems.

Thanks for helping me out 🤗
