### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by fdncred** [nushell/tree-sitter-nu#157]
reported from discord.
![image](https://github.com/user-attachments/assets/4cdb47f3-d597-480b-be36-7f3e352828e5)

```nushell
export def main [] {
    let input = $in

    let regex = r#'(</?[\w-]+(?:\s+[\w-]+(?: = (?:"[^"]*"|\'[^\']*\'|[^\s>]+))?)*\s*/?>)'#
    let regex = ($regex | str replace -a ' ' '')

    let matches = ($input | parse -r $regex | get capture0)
    let contents = ($input | split row -r $regex | skip)
    let zips = ($matches | zip $contents)

    mut stack = []
    mut result = []
 }
```

Not sure if this is part of the quoting problem or the new raw string support?

**Comment by fdncred** [comment]
It's interesting that deleting the `l` makes the raw string part parse correctly.
![image](https://github.com/user-attachments/assets/544b36a1-a1e9-4236-bef5-3a0485f40ff2)

**Comment by blindFS** [comment]
A minimal reproduction of the error:

<img width="115" alt="image" src="https://github.com/user-attachments/assets/1d3f4383-7070-4404-801a-acf565db9540">

leading whitespaces not skipped by `extras`, seems a bug of ts for me, but I guess we can hack it in scanner.c

**Comment by fdncred** [comment]
whatever you think the best way to fix it is, is fine with me.
