### ISSUE TITLE
Neovim crashes once a nu file is opened on windows

### ISSUE THREAD

**Issue by road2coder** [nushell/tree-sitter-nu#164]
here is my treesitter config:
```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      { "nushell/tree-sitter-nu", build = ":TSUpdate nu" },
    },
    keys = {
      { "<c-space>", false },
      { "<bs>", false },
    },
    opts = {
      ensure_installed = { "nu" },
      incremental_selection = {
        enable = true,
        keymaps = {
          node_incremental = "<A-l>",
          init_selection = "<A-l>",
          scope_incremental = false,
          node_decremental = "<A-h>",
        },
      },
    },
  },
}
```

**Comment by blindFS** [comment]
First of all, try to upgrade nvim-treesitter to the latest commit and reinstall the parser. If still no good, your nvim version can be helpful to identify the problem.

**Comment by road2coder** [comment]
Hi, @blindFS 

> First of all, try to upgrade nvim-treesitter to the latest commit and reinstall the parser. If still no good, your nvim version can be helpful to identify the problem.

Works fine with latest commit. thank you.
