### ISSUE TITLE
100% CPU usage in new example configuration

### ISSUE THREAD

**Issue by PerchunPak** [nushell/tree-sitter-nu#170]
(to be clear, 100% of one CPU core; but that still feels incredibly laggy)

![image](https://github.com/user-attachments/assets/4fa55314-cdb2-4802-bc8c-a6c4b329c392)

starting at this line https://github.com/nushell/nushell/blob/39770d41975a0dae3cdc89802215416a4c6671e4/crates/nu-utils/src/default_files/sample_config.nu#L376

**Comment by fdncred** [comment]
I experienced it too.

I load the file and everything is fine. Then I searched like `/Misc`. Once I found it, moving up and down caused the lines to change color from green to white and it's super laggy and using way too much CPU.

![image](https://github.com/user-attachments/assets/874e4bec-51d2-4f38-850a-7e2cb1caa2f2)

**Comment by fdncred** [comment]
@blindFS no, it's not. I think @NotTheDr01ds has a PR to clean up those files.

**Comment by PerchunPak** [comment]
The PR didn't fix the issue, I still have 100% CPU usage after updating and ensuring newer queries are installed
