### ISSUE TITLE
Interpolated strings produce a lot of nodes

### ISSUE THREAD

**Issue by mikayla-maki** [nushell/tree-sitter-nu#29]
At Zed we have a tool built into our editor for examining the syntax tree for any buffer we have open. While using this to add nu syntax highlighting to Zed, I noticed that there is a new tree sitter node being added for every character in an interpolated string. I expect this isn't the intended behavior so I thought I'd let y'all know 🙂

<img width="896" alt="Screenshot 2023-09-09 at 3 51 12 PM" src="https://github.com/nushell/tree-sitter-nu/assets/2280405/6d8a6d30-795c-49f8-96a5-84ea01d20f82">

**Comment by mikayla-maki** [comment]
For reference, here's how javascript's treesitter parses a similar file:
 
<img width="1233" alt="Screenshot 2023-09-09 at 3 55 56 PM" src="https://github.com/nushell/tree-sitter-nu/assets/2280405/27e05f9d-56ec-4c09-b144-e86ee437347f">

**Comment by fdncred** [comment]
Thanks @mikayla-maki, Appreciate the info. The core-team at nushell is not very good at tree-sitter. In fact, most of this repo was from the community mostly by @1Kinoti. We'd love to have more people contributing to this repo to make our editor experience a bit better.

**Comment by 1Kinoti** [comment]
thanks @mikayla-maki.

i already have a fix for this issue in mind and will make a pr for it.

**Comment by fdncred** [comment]
yay @1Kinoti's back. Good to see you around here again! ❤️

**Comment by 1Kinoti** [comment]
thanks @fdncred.

**Comment by fdncred** [comment]
fixed by #30
