### ISSUE TITLE
syntax highlighting gets confused

### ISSUE THREAD

**Issue by fdncred** [nushell/tree-sitter-nu#31]
Trying out Zed with nu highlighting I found this in default_env.nu. Notice that after the pipe, it stops highlighting.

![image](https://github.com/nushell/tree-sitter-nu/assets/343840/b5c4bc89-3fff-4688-a96a-7dc1de24ea7d)

Looking at the `Syntax Tree` windows in Zed, there are a few `ERROR`s.

![image](https://github.com/nushell/tree-sitter-nu/assets/343840/a5760ea3-0de8-4394-a0c2-a82c6c6b7843)

It would be nice to get this fixed in order to have a more pleasant experience in Zed.

**Comment by amtoine** [comment]
@fdncred 
could you share the source code of this so that i can dump it inside Neovim and see if i get the same? :innocent: 

i think i've seen this before and suspect it's getting confused around the strings / quotes :thinking:

**Comment by fdncred** [comment]
@amtoine The file is the default_env.nu.
