### ISSUE TITLE
Parser breaks with this syntax

### ISSUE THREAD

**Issue by marcelarie** [nushell/tree-sitter-nu#32]
With the `type@'type'` on the command parameter, the syntax highlighting breaks.

Example of the code:
```nu
export def-env main [
	command?: string@'nu-complete rbenv',
	...args
] {
    let new_env = if $command in ["rehash", "shell"] {
        # implement each on indiviudaly e.g.
        if $command == "shell" {
            { RBENV_VERSION_OLD: $env.RBENV_VERSION RBENV_VERSION: $args.0 }
        } else {
            error make { msg: $"`($command)` command is not supported yet" }
        }
    } else {
    	if ($command | is-empty) {
    		^rbenv
    	} else {
        	^rbenv $command $args
    	}
        {}
    }
    load-env $new_env
}

def 'nu-complete rbenv' [] {
    ^rbenv help
    | lines
    | where ($it | str starts-with "   ")
    | each {|entry| $entry | split row ' ' | get 0 }
}
```

Screenshoot:
<img width="794" alt="Screenshot 2023-09-24 at 23 38 56" src="https://github.com/nushell/tree-sitter-nu/assets/62728887/03230c4c-4fc5-41fc-a984-0be7edcd46d3">

**Comment by fdncred** [comment]
Thanks for the report! We need more hands on this repo. We only have a couple people who've done 99% of the work. Feel free to get your hands dirty and try to submit a PR.

**Comment by amtoine** [comment]
not sure i see the same in Neovim :open_mouth: 
![tree-sitter-nu_32](https://github.com/nushell/tree-sitter-nu/assets/44101798/b9e6fc78-ed0b-418e-908b-0df3527f5f24)

**Comment by marcelarie** [comment]
I am using neovim too, how strange. Maybe I have some plugin that breaks treesitter.


https://github.com/nushell/tree-sitter-nu/assets/62728887/a38bd21b-3405-488c-977e-ebcdc8cf2611

**Comment by amtoine** [comment]
:scream: 

without looking at the config, the only difference i see is the extra `export-env` block you have at the top :smirk: 

also, do you use the latest version of this TS?

**Comment by marcelarie** [comment]
I use the latest version I think, how can I check it?

**Comment by siph** [comment]
fwiw this highlighting looks fine with my neovim config as well.

**Comment by amtoine** [comment]
> I use the latest version I think, how can I check it?
>
not sure, i've installed the queries from this repo manually so i do not have the revision attached to them i fear :confused:

**Comment by amtoine** [comment]
very strange, i just pulled the query file again and reinstalled the TS parser again with the following two scripts:
- [`toolkit update`](https://github.com/goatfiles/kickstart.nvim/blob/c9799a6/toolkit.nu#L107-L110) which calls...
- ... [`install-queries`](https://github.com/goatfiles/kickstart.nvim/blob/c9799a6/toolkit.nu#L3-L22)

and i still do not see this :cry:

**Comment by petrisch** [comment]
Did you check the :InspectTree for this?
Cause with my colorscheme this doesn't break the highlight,
however I see an ERROR on this line (26):
`    | where ($it | str starts-with "   ")`
right on the `where` keyword.

**Comment by petrisch** [comment]
I don't have a solution, but shouldn't there be optional punctuation, like brakets or parenthesis in the _where_predicate here?

```js
where_command: ($) => seq("where", $._where_predicate),

    _where_predicate: ($) =>
      choice(
        ...TABLE().map(([precedence, opr]) =>
          prec.left(
            precedence,
...
```
Because this:
```nu
[["a" "b"];[3 4] [5 6]] | where ("a" < 4)
```
or this
```nu
[["a" "b"];[3 4] [5 6]] | where "a" < 4
```
breaks it for me also.

**Comment by fdncred** [comment]
`where` can have parentheses or braces since it's a closure.

**Comment by fdncred** [comment]
I'm not seeing any errors in the OP's script now (except moving from `def-env` to `def --env`). So, I'm closing this.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/53a328f7-1493-4861-8139-d6ba78b02a38)

**Comment by kit494way** [comment]
yes. I will try.
