### ISSUE TITLE
Exports fail to highlight after first occurence

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/tree-sitter-nu#34]
Zed
<img width="628" alt="SCR-20231129-pcpz" src="https://github.com/nushell/tree-sitter-nu/assets/19867440/876f4d42-a0b1-4f0d-ac21-1d6fb8aa0e8f">

Helix
<img width="351" alt="SCR-20231129-pcts" src="https://github.com/nushell/tree-sitter-nu/assets/19867440/ca37e633-1abd-49de-9d5c-0e61cfd4a01b">

```nu
export const GAMMA = 0.5772156649015329
export const E = 2.718281828459045
export const PI = 3.141592653589793
export const TAU = 6.283185307179586
export const PHI = 1.618033988749895
```

https://github.com/nushell/nushell/blob/main/crates/nu-std/std/math.nu

**Comment by fdncred** [comment]
We definitely need some help with tree-sitter. It's pretty foreign to most of our maintainers.
