### ISSUE TITLE
The line after an empty comment is parsed as a comment.

### ISSUE THREAD

**Issue by kit494way** [nushell/tree-sitter-nu#41]
```nu
#
echo hello
```

![スクリーンショット 2023-12-24 140624](https://github.com/nushell/tree-sitter-nu/assets/17674842/9970cefa-9132-480d-a0a2-d814838e5e35)

**Comment by amtoine** [comment]
aah yeah, i've seen this one a bunch of times :+1:

**Comment by fdncred** [comment]
sounds like a bug. thanks.
