### ISSUE TITLE
Parsing of re-export module fails

### ISSUE THREAD

**Issue by kit494way** [nushell/tree-sitter-nu#42]
https://github.com/nushell/nushell/blob/b0b4c3dffd9f84ea18236e8f9055d642de029a1d/crates/nu-std/std/mod.nu#L1-L18

![スクリーンショット 2023-12-24 142541](https://github.com/nushell/tree-sitter-nu/assets/17674842/e6dec256-e92e-494c-be94-3c5df5b7163e)

**Comment by fdncred** [comment]
looks like another bug. thanks.
