### ISSUE TITLE
Highlighting breaks on `alias` before `let`

### ISSUE THREAD

**Issue by stevenxxiu** [nushell/tree-sitter-nu#45]
The following breaks:

```nushell
alias less = bat
let foo = $'($env.HOME)'
```

It's fine when `alias` is removed.

**Comment by amtoine** [comment]
here's how it looks like
![nu-bad-highlight](https://github.com/nushell/tree-sitter-nu/assets/44101798/c4e0b8dc-9066-44fa-9933-502f1d6aea0d)

**Comment by fdncred** [comment]
I'm trying to understand if this is in an editor or on the repl. This is what I get on the repl.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/ae0515e0-a5dd-4370-9efc-aeaca7f893f7)
and in vscode
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/71b2e4e3-8b02-477b-81c5-107c025ca1be)

**Comment by stevenxxiu** [comment]
I tested it in *Neovim*. It looks fine for me on the REPL.

**Comment by fdncred** [comment]
ok, thanks. This is what I get in helix with edbb7ddb42205aa040b7b1255b9cf56e387c433f commit.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/9830d58a-bed1-4254-926a-23dfc9cbda3a)

I don't have tree-sitter-nu installed in nushell.

**Comment by stevenxxiu** [comment]
> I don't have tree-sitter-nu installed in nushell.

Ah nor do I. Thanks, I wasn't aware it could be installed for *Nushell*.

**Comment by fdncred** [comment]
oops, I meant neovim. Sorry.
