### ISSUE TITLE
Fails to parse a multi-line command enclosed in parentheses

### ISSUE THREAD

**Issue by kit494way** [nushell/tree-sitter-nu#47]
![スクリーンショット 2023-12-26 203324](https://github.com/nushell/tree-sitter-nu/assets/17674842/edea1ddd-2124-4a0d-9cf7-d5da1990623f)

**Comment by amtoine** [comment]
not sure i get what the issue here is :open_mouth: 
the highlighting to the right looks right

**Comment by kit494way** [comment]
> Everything inside of the parentheses are treated as if they were written together
https://www.nushell.sh/blog/2021-07-13-nushell_0_34.html#improved-multiline-support-jt

Highlighting of `two` is wrong. It must be treated as an argument of `echo`.
The result of executing the above command is as follows.

![スクリーンショット 2023-12-26 214336](https://github.com/nushell/tree-sitter-nu/assets/17674842/76ac0ca8-e359-43e4-a1a5-5e508f99bbc6)

**Comment by amtoine** [comment]
aah yeah, my bad, it's in a subexpression :+1:
