### ISSUE TITLE
Parsing of pipeline fails when the first pipeline element is variable or control expression, and there is a newline before the next element

### ISSUE THREAD

**Issue by kit494way** [nushell/tree-sitter-nu#52]
Example 1.
![スクリーンショット 2024-01-02 145803](https://github.com/nushell/tree-sitter-nu/assets/17674842/211e7906-ecbe-4260-a1dc-be262687c26c)

Example 2.
![スクリーンショット 2024-01-02 151850](https://github.com/nushell/tree-sitter-nu/assets/17674842/28d887f5-401d-41ff-9f12-18477829ba32)

In Example 1, `match` expression must be parsed as a `pipe_element` but it is not.
And entire script must be parsed as a `pipeline` but it is not.

In Example 2, `$xs` and `| each {|x| $x }` must be parsed as `pipe_element` of same `pipeline` but they are not.

**Comment by fdncred** [comment]
Agreed. When I edit nushell's toolkit.nu in helix and notice this frequently. I also notice this if/else section that is parsed and colored wrong, although unrelated to this. Just thought I'd mention it.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/a049fa9d-e490-4ac5-9bad-48219eb8f8ad)

**Comment by kit494way** [comment]
I created another issue for the case if/else section is parsed incorrectly.
