### ISSUE TITLE
Parsing of range fails

### ISSUE THREAD

**Issue by kit494way** [nushell/tree-sitter-nu#53]
![スクリーンショット 2024-01-02 172309](https://github.com/nushell/tree-sitter-nu/assets/17674842/9f8fa2ce-c491-4ba5-ba48-4d17cc4bb645)

This bug is introduced by this change #50.
It seems that the rule, which parses a number omitted after decimal point (e.g. `1.`) as float, parses head of range value as float incorrectly.

**Comment by fdncred** [comment]
oh, ya. good catch. i hadn't noticed this one.
