### ISSUE TITLE
Incorrect parsing for long param flag with dashes

### ISSUE THREAD

**Issue by fredericgiquel** [nushell/tree-sitter-nu#54]
First example:
```nu
#!/usr/bin/env nu

def main [
  --long-param-with-dashes
  --long_param_with_underscores
] {
  if $long_param_with_dashes {
    print "dash param"
  } else {
    print "no dash param"
  }

  if $long_param_with_underscores {
    print "underscore param"
  } else {
    print "no underscore param"
  }
}
```
Syntax highlighting is incorrect and there are multiple "param_short_flag" for the first param flag (with dashes):
![tree-sitter-nu1](https://github.com/nushell/tree-sitter-nu/assets/17704127/887699f7-e6a6-4335-9965-0c4b88acb475)

Second example (probably same cause but different effect):
```nu
#!/usr/bin/env nu

def main [
  --dry-run (-n)
] {
  if $dry_run {
    print "Dry run"
  } else {
    print "Real execution"
  }
}
```
There is now an error in the tree:
![tree-sitter-nu2](https://github.com/nushell/tree-sitter-nu/assets/17704127/045070b5-9397-49d6-b2d3-dba4b174b77e)

**Comment by fdncred** [comment]
nice catch! thanks. I hadn't noticed this yet.
