### ISSUE TITLE
A newline between `}` and `else` cause parse error

### ISSUE THREAD

**Issue by kit494way** [nushell/tree-sitter-nu#58]
A newline between `}` and `else` is allowed only if it is parenthesized.
This is originally reported in this [comment](https://github.com/nushell/tree-sitter-nu/issues/52#issuecomment-1874017078).

![スクリーンショット 2024-01-03 153748](https://github.com/nushell/tree-sitter-nu/assets/17674842/a879306e-8753-42ab-aef3-b77d36c7e909)

**Comment by kubouch** [comment]
This is a limitation of Nushell's syntax in general. You can't place `else` on a new line without parens, currently, because it looks like another command call.

**Comment by kit494way** [comment]
try/catch has the same issue.

**Comment by fdncred** [comment]
> This is a limitation of Nushell's syntax in general. You can't place `else` on a new line without parens, currently, because it looks like another command call.

@kubouch It works but looks ugly. My example was from the toolkit.nu in the root of the nushell repo.
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/d83d9ed3-5415-49f8-a1ea-b7c77e9c2fec)

**Comment by kubouch** [comment]
Ah, I see, it needs to be in parens.

**Comment by fdncred** [comment]
Looks much better now
![image](https://github.com/nushell/tree-sitter-nu/assets/343840/34a39931-3718-4c3c-95f7-110e770ca081)
