### ISSUE TITLE
Closure parsed as a record

### ISSUE THREAD

**Issue by fredericgiquel** [nushell/tree-sitter-nu#67]
In the following example:
```nu
#!/usr/bin/env nu

let $list = [a b c d]

# Correctly parsed
$list | filter {|x| $x | str starts-with c }

# Still valid but not correctly parsed
$list | filter { str starts-with c }
```

The closure for filter command is incorrectly parsed in the last line. And this leads to an error in the tree.
![tree-sitter-nu3](https://github.com/nushell/tree-sitter-nu/assets/17704127/efebd535-bca4-4fb8-8012-be693821edf5)

**Comment by fdncred** [comment]
Thanks. Do you know if this is with the latest main branch of this repo? There have been a lot of changes recently.

**Comment by fredericgiquel** [comment]
Yes. It's with the latest commit in main branch.

**Comment by kit494way** [comment]
same issue #16
