### ISSUE TITLE
`inf` is parsed as a number unless quoted

### ISSUE THREAD

**Issue by siph** [nushell/tree-sitter-nu#77]
`tree-sitter-nu` version: 2d0dd587dbfc3363d2af4e4141833e718647a67e
![Screenshot_20240125_140016](https://github.com/nushell/tree-sitter-nu/assets/6619112/5953c999-b84e-467e-9474-79fc76463fbb)

**Comment by fdncred** [comment]
There's also the `debug info` command where I guess this would break?

**Comment by siph** [comment]
Here's a more exhaustive example:
![Screenshot_20240125_152502](https://github.com/nushell/tree-sitter-nu/assets/6619112/d1c7e315-3a27-453f-b5e4-e07f84b6f510)
