### ISSUE TITLE
Wrong highlighting in if else statement.

### ISSUE THREAD

**Issue by BigCrow** [nushell/tree-sitter-nu#88]
Treesitter highlighting fails when else flag is missing a closure ``else $statement``.

**Look at the let keywords below.**
Example without closure:
![image](https://github.com/nushell/tree-sitter-nu/assets/1347244/781ea53a-ce2b-4d7d-9eef-ab139c21176b)
Example with closure:
![image](https://github.com/nushell/tree-sitter-nu/assets/1347244/3fb35c87-550e-483a-9e37-79065ea72496)

Tested in neovim.

**Comment by fdncred** [comment]
I'm guessing that this has something to do with https://github.com/nushell/tree-sitter-nu/blob/main/queries/nu/highlights.scm. I think it's been a while since the highlights.scm file was updated. I was looking at it last week and noticed that some of the grammar isn't in the file at all. It deserves a good run through if someone has the time.

**Comment by BigCrow** [comment]
I think it is straight up a problem with the grammar rather than highlighting. TSPlayground is identifying the let keyword with identifier instead: 
![image](https://github.com/nushell/tree-sitter-nu/assets/1347244/bfff0926-7146-478b-b5b7-443230e6e3cd)

Here how it should look:
![image](https://github.com/nushell/tree-sitter-nu/assets/1347244/7d09f2f7-ce24-4558-82f1-5e0f3b2660bc)

**Comment by fdncred** [comment]
@kit494way any thoughts on this? Do you have time to help update the grammar?

**Comment by BigCrow** [comment]
In the grammar.js on lines 348 & 366 you have this rule for the else statement:
```js
              field("else_block", $.block),
```
however the else block can actually take a lot more (compared to if which can indeed only take a block). Adding expressions & commands seems to work for the most part:
```js
                field("else_block", choice($.block, $._expression, $.cmd_identifier)),
```
Any idea on any other potential elements that could be put after an else?
