### ISSUE TITLE
Add support for new nushell feature - raw strings

### ISSUE THREAD

**Issue by CabalCrow** [nushell/tree-sitter-nu#97]
https://www.nushell.sh/blog/2024-05-28-nushell_0_94_0.html#new-language-feature-raw-strings-toc

**Comment by mrdgo** [comment]
I'll take a look. This will probably require a [custom scanner](https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners) - so it'll likely take a bit longer  to pull off.

**Comment by fdncred** [comment]
closed by https://github.com/nushell/tree-sitter-nu/pull/113
